<?php

return [
    [
        'marque' => 'Renault',
        'modele' => 'Expresse',
        'annee' => 2020,
        'categorie' => 'berlines',
        'prix_journalier' => 350.00,
        'disponible' => true,
        'image' => 'voitures/express.jpg',
        'description' => 'Véhicule utilitaire compact et robuste, idéal pour les professionnels ayant besoin de transporter du matériel.',
        'carburant' => 'Diesel',
        'transmission' => 'Manuelle',
        'nombre_places' => 3,
        'nombre_portes' => 5,
        'climatisation' => true,
        'gps' => false,
        'musique' => true
    ],
    [
        'marque' => 'Seat',
        'modele' => 'Ibiza',
        'annee' => 2024,
        'categorie' => 'Citadine',
        'prix_journalier' => 400.00,
        'disponible' => true,
        'image' => 'voitures/ibiza.png',
        'description' => 'Petite voiture urbaine alliant style dynamique, faible consommation et technologies modernes, idéale pour les trajets en ville.',
        'carburant' => 'Électrique',
        'transmission' => 'Automatique',
        'nombre_places' => 5,
        'nombre_portes' => 2,
        'climatisation' => true,
        'gps' => false,
        'musique' => true
    ],
    [
        'marque' => 'Peugeot',
        'modele' => '208',
        'annee' => 2024,
        'categorie' => 'Citadine',
        'prix_journalier' => 350.00,
        'disponible' => true,
        'image' => 'voitures/208.jpg',
        'description' => 'Petite voiture au style distinctif, réputée pour son confort de conduite, ses motorisations efficientes et son intérieur soigné.',
        'carburant' => 'Essence',
        'transmission' => 'Automatique',
        'nombre_places' => 3,
        'nombre_portes' => 2,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Renault',
        'modele' => 'Clio',
        'annee' => 2024,
        'categorie' => 'Citadine',
        'prix_journalier' => 281.00,
        'disponible' => true,
        'image' => 'voitures/clio.webp',
        'description' => 'Citadine polyvalente et moderne, très appréciée pour son design élégant et sa technologie embarquée.',
        'carburant' => 'Diesel',
        'transmission' => 'Manuelle',
        'nombre_places' => 6,
        'nombre_portes' => 3,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Volkswagen',
        'modele' => 'Touareg',
        'annee' => 2024,
        'categorie' => 'suv',
        'prix_journalier' => 2500.00,
        'disponible' => true,
        'image' => 'voitures/touareg.jpg',
        'description' => 'Grand SUV raffiné, doté d\'un habitacle luxueux, de technologies avancées et d\'un confort remarquable.',
        'carburant' => 'Diesel',
        'transmission' => 'Manuelle',
        'nombre_places' => 7,
        'nombre_portes' => 2,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Seat',
        'modele' => 'Ateca',
        'annee' => 2023,
        'categorie' => 'SUV',
        'prix_journalier' => 900.00,
        'disponible' => false,
        'image' => 'voitures/ateca.png',
        'description' => 'SUV compact polyvalent, offrant une conduite surélevée, un bon espace intérieur et des performances fiables.',
        'carburant' => 'Diesel',
        'transmission' => 'Automatique',
        'nombre_places' => 5,
        'nombre_portes' => 3,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Opel',
        'modele' => 'Mokka',
        'annee' => 2024,
        'categorie' => 'Crossover',
        'prix_journalier' => 165.00,
        'disponible' => true,
        'image' => 'voitures/mokka.jpg',
        'description' => 'Crossover élégant et compact, avec un design moderne et une motorisation économique, parfait pour la ville et les escapades.',
        'carburant' => 'Hybride',
        'transmission' => 'Automatique',
        'nombre_places' => 7,
        'nombre_portes' => 2,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Opel',
        'modele' => 'Corsa',
        'annee' => 2024,
        'categorie' => 'Citadine',
        'prix_journalier' => 350.00,
        'disponible' => true,
        'image' => 'voitures/corsa.jpg',
        'description' => 'Voiture compacte pratique et maniable, conçue pour la conduite urbaine avec un bon niveau d\'équipements.',
        'carburant' => 'Diesel',
        'transmission' => 'Automatique',
        'nombre_places' => 5,
        'nombre_portes' => 3,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Cupra',
        'modele' => 'Formentor',
        'annee' => 2021,
        'categorie' => 'Sportif',
        'prix_journalier' => 1500.00,
        'disponible' => true,
        'image' => 'voitures/formentor.webp',
        'description' => 'SUV sportif et premium, combinant performance, technologie de pointe et design agressif.',
        'carburant' => 'Diesel',
        'transmission' => 'Automatique',
        'nombre_places' => 2,
        'nombre_portes' => 5,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Cupra',
        'modele' => 'Leon',
        'annee' => 2025,
        'categorie' => 'berlines',
        'prix_journalier' => 271.00,
        'disponible' => true,
        'image' => 'voitures/lion.png',
        'description' => 'Berline compacte au caractère sportif, offrant une excellente tenue de route et une motorisation puissante.',
        'carburant' => 'Essence',
        'transmission' => 'Manuelle',
        'nombre_places' => 2,
        'nombre_portes' => 5,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Range Rover',
        'modele' => 'Sport',
        'annee' => 2025,
        'categorie' => 'SUV',
        'prix_journalier' => 5000.00,
        'disponible' => true,
        'image' => 'voitures/rang.webp',
        'description' => 'SUV haut de gamme alliant luxe, puissance et capacités tout-terrain exceptionnelles.',
        'carburant' => 'Hybride',
        'transmission' => 'Automatique',
        'nombre_places' => 5,
        'nombre_portes' => 2,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Audi RS3',
        'modele' => 'Sportback',
        'annee' => 2025,
        'categorie' => 'Sportive',
        'prix_journalier' => 6000.00,
        'disponible' => true,
        'image' => 'voitures/rs3s.jpg',
        'description' => 'Compacte sportive à hayon offrant des performances impressionnantes, un style affirmé et une technologie de pointe.',
        'carburant' => 'Diesel',
        'transmission' => 'Automatique',
        'nombre_places' => 3,
        'nombre_portes' => 4,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Mercedes G63',
        'modele' => 'AMG',
        'annee' => 2019,
        'categorie' => 'SUV',
        'prix_journalier' => 10000.00,
        'disponible' => true,
        'image' => 'voitures/g63.jpg',
        'description' => '4x4 emblématique au style unique, combinant puissance brute, luxe et capacités off-road exceptionnelles.',
        'carburant' => 'Essence',
        'transmission' => 'Manuelle',
        'nombre_places' => 5,
        'nombre_portes' => 4,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Volkswagen',
        'modele' => 'Polo',
        'annee' => 2024,
        'categorie' => 'Citadine',
        'prix_journalier' => 3000.00,
        'disponible' => true,
        'image' => 'voitures/polo8.jpg',
        'description' => 'Citadine spacieuse et bien équipée, alliant fiabilité, confort et consommation maîtrisée.',
        'carburant' => 'Essence',
        'transmission' => 'Automatique',
        'nombre_places' => 6,
        'nombre_portes' => 2,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Peugeot',
        'modele' => '2008',
        'annee' => 2024,
        'categorie' => 'Crossover',
        'prix_journalier' => 1500.00,
        'disponible' => true,
        'image' => 'voitures/2008.jpg',
        'description' => 'SUV urbain au design affirmé, combinant modularité, connectivité et plaisir de conduite.',
        'carburant' => 'Diesel',
        'transmission' => 'Manuelle',
        'nombre_places' => 7,
        'nombre_portes' => 4,
        'climatisation' => false,
        'gps' => false,
        'musique' => true
    ],
    [
        'marque' => 'Toyota',
        'modele' => 'Yaris Cros',
        'annee' => 2024,
        'categorie' => 'Crossover',
        'prix_journalier' => 700.00,
        'disponible' => true,
        'image' => 'voitures/yaris.webp',
        'description' => 'Petit SUV hybride, fiable et économique, parfait pour les trajets quotidiens et les petites aventures.',
        'carburant' => 'Essence',
        'transmission' => 'Manuelle',
        'nombre_places' => 6,
        'nombre_portes' => 3,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Renault',
        'modele' => 'Arkana',
        'annee' => 2024,
        'categorie' => 'SUV',
        'prix_journalier' => 1100.00,
        'disponible' => true,
        'image' => 'voitures/arkana.webp',
        'description' => 'SUV au style coupé, moderne et spacieux, qui combine élégance et fonctionnalité.',
        'carburant' => 'Électrique',
        'transmission' => 'Manuelle',
        'nombre_places' => 4,
        'nombre_portes' => 2,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Seat',
        'modele' => 'Arona',
        'annee' => 2022,
        'categorie' => 'crossover',
        'prix_journalier' => 800.00,
        'disponible' => true,
        'image' => 'voitures/arona.jpg',
        'description' => 'Petit SUV , fiable et économique, parfait pour les trajets quotidiens et les petites aventures.',
        'carburant' => 'Diesel',
        'transmission' => 'Manuelle',
        'nombre_places' => 4,
        'nombre_portes' => 4,
        'climatisation' => false,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Dacia',
        'modele' => 'Duster',
        'annee' => 2025,
        'categorie' => 'Crossover',
        'prix_journalier' => 600.00,
        'disponible' => true,
        'image' => 'voitures/duster.webp',
        'description' => 'style coupé, moderne et spacieux, qui combine élégance et fonctionnalité.',
        'carburant' => 'Diesel',
        'transmission' => 'Automatique',
        'nombre_places' => 3,
        'nombre_portes' => 4,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Dacia',
        'modele' => 'Stepway',
        'annee' => 2024,
        'categorie' => 'crossover',
        'prix_journalier' => 185.00,
        'disponible' => true,
        'image' => 'voitures/stepway.webp',
        'description' => 'Citadine spacieuse et bien équipée, alliant fiabilité, confort et consommation maîtrisée.',
        'carburant' => 'Électrique',
        'transmission' => 'Manuelle',
        'nombre_places' => 5,
        'nombre_portes' => 3,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Mercedes',
        'modele' => 'C220',
        'annee' => 2023,
        'categorie' => 'Berline',
        'prix_journalier' => 104.00,
        'disponible' => true,
        'image' => 'voitures/c220.jpg',
        'description' => 'Citadine spacieuse et bien équipée, alliant fiabilité, confort et consommation maîtrisée.',
        'carburant' => 'Essence',
        'transmission' => 'Automatique',
        'nombre_places' => 5,
        'nombre_portes' => 5,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ],
    [
        'marque' => 'Audi rs3',
        'modele' => 'Sedan',
        'annee' => 2024,
        'categorie' => 'Berline',
        'prix_journalier' => 2500.00,
        'disponible' => true,
        'image' => 'voitures/r3.jpg',
        'description' => 'Compacte sportive à hayon offrant des performances impressionnantes, un style affirmé et une technologie de pointe.',
        'carburant' => 'Hybride',
        'transmission' => 'Automatique',
        'nombre_places' => 4,
        'nombre_portes' => 3,
        'climatisation' => true,
        'gps' => false,
        'musique' => true
    ],
    [
        'marque' => 'Volkswagen',
        'modele' => '8 r line',
        'annee' => 2024,
        'categorie' => 'cabriolets',
        'prix_journalier' => 3500.00,
        'disponible' => true,
        'image' => 'voitures/8r.jpg',
        'description' => 'Citadine spacieuse et bien équipée, alliant fiabilité, confort et consommation maîtrisée.',
        'carburant' => 'Diesel',
        'transmission' => 'Automatique',
        'nombre_places' => 6,
        'nombre_portes' => 3,
        'climatisation' => true,
        'gps' => true,
        'musique' => true
    ]
];
